# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea7eb1675b667bf2c667cc8fa28c7fd7ca9f871ca33b8cbc5737205828df6121939cf7b98ba8215472e8be29c4a6d0288a4fdf5799ac67ff34843948a02a8f2c

test:
  secret_key_base: e812c1c195f16961b1a6d78e1b45368a6aae1f3e1c290990a3e5645b053856806b6d953d056d143937759632867ec0aad02e6c3e8c2eceac9a2ecf960b523ec4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
